import CryptoKit
import Foundation
import LocalAuthentication
import S1Support
import Security

// s1-fixtures [--out PATH]   writes fixtures/se-mac.json (Secure Enclave + software CryptoKit outputs for Python to verify)
// s1-fixtures --presence     MANUAL: creates an SE key with .userPresence (Touch ID / passcode prompt) and signs once.
//                            Not used by tests: it blocks on a human.

func fail(_ m: String) -> Never { FileHandle.standardError.write(Data((m + "\n").utf8)); exit(1) }

let args = CommandLine.arguments
let accessible = kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly

func accessControl(_ flags: SecAccessControlCreateFlags) -> SecAccessControl {
    var err: Unmanaged<CFError>?
    guard let ac = SecAccessControlCreateWithFlags(nil, accessible, flags, &err) else { fail("access control: \(err!.takeRetainedValue())") }
    return ac
}

if args.contains("--presence") {
    guard SecureEnclave.isAvailable else { fail("no Secure Enclave") }
    // .privateKeyUsage | .userPresence: every signature prompts for Touch ID or the device passcode.
    let ctx = LAContext()
    ctx.localizedReason = "orch S1 spike: sign one test message"
    let key = try SecureEnclave.P256.Signing.PrivateKey(compactRepresentable: false,
                                                        accessControl: accessControl([.privateKeyUsage, .userPresence]),
                                                        authenticationContext: ctx)
    print("created presence-gated key, pub x963 = \(key.publicKey.x963Representation.hex)")
    print("signing now: expect a Touch ID / password prompt ...")
    let msg = Data("orch v2 presence test".utf8)
    let sig = try key.signature(for: msg)
    print("verified: \(key.publicKey.isValidSignature(sig, for: msg)), sig = \(sig.rawRepresentation.hex)")
    exit(0)
}

var outPath = Vectors.repoRoot().appendingPathComponent("spikes/s1/fixtures/se-mac.json").path
if let i = args.firstIndex(of: "--out"), i + 1 < args.count { outPath = args[i + 1] }

guard SecureEnclave.isAvailable else { fail("SecureEnclave.isAvailable == false: cannot write the SE fixture on this machine") }

let v = try Vectors.load()
let s2 = try Vectors.suite2(v)
let labels = try Labels(v)
let keys = s2["keys"] as! [String: [String: String]]
let ids = s2["ids"] as! [String: String]
let vecKx = try kxKey(seed: try Data(hex: keys["laptop.kx"]!["seed"]!))   // peer for ECDH
let vecPhoneKx = try kxKey(seed: try Data(hex: keys["phone.kx"]!["seed"]!))

func sigEntry(_ msg: Data, _ sig: P256.Signing.ECDSASignature) -> [String: Any] {
    ["msg": msg.hex, "sig_raw": sig.rawRepresentation.hex, "sig_der": sig.derRepresentation.hex]
}

let msgs = ["orch v2 signature vector", "", "second message \u{1F512}"].map { Data($0.utf8) }

// --- Secure Enclave signing key
let seSig = try SecureEnclave.P256.Signing.PrivateKey(accessControl: accessControl(.privateKeyUsage))
let seSigCases = try msgs.map { sigEntry($0, try seSig.signature(for: $0)) }

// --- Secure Enclave key agreement vs a vector software key (laptop.kx)
let seKx = try SecureEnclave.P256.KeyAgreement.PrivateKey(accessControl: accessControl(.privateKeyUsage))
let ss = rawBytes(try seKx.sharedSecretFromKeyAgreement(with: vecKx.publicKey))
let ecdh: [String: Any] = ["se_kx_pub": seKx.x963, "peer_vector_key": "laptop.kx", "shared_secret": ss.hex]
    .mapValues { ($0 as? Data)?.hex ?? $0 }

// --- seal with the SE key as the sender's ephemeral key, to the vector phone.kx key (Python opens it)
let rcptID = try Data(hex: ids["device_phone"]!), objectID = try Data(hex: ids["workspace_a"]!)
let plaintext = try Data(hex: "25f9c35cafc016ffc1633cdfa8f9cd0bfe3d17b70fdd62f6289184539eeadc4f")
let seSealed = try sealTo(labels, eph: seKx, rcptPub: vecPhoneKx.x963, rcptID: rcptID, purpose: "wk", objectID: objectID, epoch: 1, plaintext: plaintext)

// --- the same with a plain software ephemeral key
let softEph = P256.KeyAgreement.PrivateKey()
let softSealed = try sealTo(labels, eph: softEph, rcptPub: vecPhoneKx.x963, rcptID: rcptID, purpose: "wk", objectID: objectID, epoch: 1, plaintext: plaintext)

// --- software CryptoKit signer
let softSig = P256.Signing.PrivateKey()
let softCases = try msgs.map { sigEntry($0, try softSig.signature(for: $0)) }

let sealBase: [String: Any] = ["purpose": "wk", "recipient_vector_key": "phone.kx", "recipient_id": rcptID.hex,
                               "object_id": objectID.hex, "epoch": 1, "plaintext": plaintext.hex]
func sealEntry(_ ephPub: Data, _ sealed: Data) -> [String: Any] {
    sealBase.merging(["eph_pub": ephPub.hex, "sealed": sealed.hex]) { a, _ in a }
}

func osVersion() -> String { ProcessInfo.processInfo.operatingSystemVersionString }

let fixture: [String: Any] = [
    "about": "Generated by spikes/s1 `swift run s1-fixtures` on a Secure Enclave Mac. Python verifies it in tests/spikes/test_s1_vectors.py. ECDSA is randomised, so signatures change on every regeneration; verification is what matters.",
    "suite": 2,
    "host": ["os": osVersion(), "secure_enclave_available": SecureEnclave.isAvailable],
    "secure_enclave": [
        "sig_pub": seSig.publicKey.x963Representation.hex,
        "sig": seSigCases,
        "ecdh": ecdh,
        "seal_with_se_ephemeral": sealEntry(seKx.x963, seSealed),
    ] as [String: Any],
    "software": [
        "sig_pub": softSig.publicKey.x963Representation.hex,
        "sig": softCases,
        "seal": sealEntry(softEph.x963, softSealed),
    ] as [String: Any],
]

let data = try JSONSerialization.data(withJSONObject: fixture, options: [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes])
try FileManager.default.createDirectory(atPath: (outPath as NSString).deletingLastPathComponent, withIntermediateDirectories: true)
try (data + Data("\n".utf8)).write(to: URL(fileURLWithPath: outPath))
print("wrote \(outPath)")
